version = 0.1

[prod]
[prod.global.parameters]
stack_name = "location-detection-prod"
region = "us-east-1"

[prod.build.parameters]
cached = true
parallel = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "us-east-1"
parameter_overrides = "Environment=\"prod\""
s3_prefix = "location-detection-prod"
image_repositories = []

[prod.package.parameters]
resolve_s3 = true

[prod.sync.parameters]
watch = true

[prod.local_start_api.parameters]
warm_containers = "EAGER"

[prod.local_start_lambda.parameters]
warm_containers = "EAGER"



